### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by yahooo-m** [Zhao-Yian/GraCo#1]
Great job!
When will you release the code?

**Comment by Zhao-Yian** [comment]
We are preparing the code as concisely as possible and optimizing the algorithm for acceleration, and will release the complete training and inference code later.

**Comment by sgzqc** [comment]
+1

**Comment by cyy-1234** [comment]
helpful

**Comment by PaPaQQQ** [comment]
+1

**Comment by yunfan1202** [comment]
+1

**Comment by chenjingong** [comment]
A nice work, interactive page can be used, can you get more contact with the author.

**Comment by chenjingong** [comment]
A nice work, interactive page can be used,? Can you get more contact with the author.

**Comment by Zhao-Yian** [comment]
I promise to release the code and weights before the end of **August**.

**Comment by yunfan1202** [comment]
> I promise to release the code and weights before the end of **August**.

Great work! Could you please just release the inference code and pre-trained weights first, even if the complete codes of the project are not well-organized currently?

**Comment by Zhao-Yian** [comment]
The code has been released, please enjoy it.

**Comment by yunfan1202** [comment]
Do you plan to release the pre-trained lora_checkpoint  named “last_checkpoint.pth” for directly running the demo.py, or did I miss something?
